version: '3.8'

services:
  # Backend server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    profiles:
      - production

  # Frontend (React app)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    profiles:
      - production

  # Nginx reverse proxy (production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    profiles:
      - production

  # Development backend
  backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
    profiles:
      - development

  # Development frontend
  frontend-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm start
    restart: unless-stopped
    profiles:
      - development

networks:
  default:
    name: smart-life-manager-network 